on:
  push:
    branches:
      - master
    paths-ignore:
      - '.*'
      - '.*/**'
  workflow_dispatch:
    inputs:
      package:
        description: Which package or commit to build (default is HEAD commit)
        required: false

jobs:
  build:
    uses: r-universe-org/workflows/.github/workflows/build.yml@reusables
    with:
      package: ${{inputs.package}}
    secrets: inherit
