on:
  workflow_dispatch:
    inputs:
      package:
        description: Which package to test
        required: true

name: Extra checks
run-name: ${{ format('Running {0} on package {1}', inputs.check, inputs.package) }}

jobs:
  check:
    name: Run extra check
    uses: r-universe/workflows/.github/workflows/recheck.yml@test
    with:
      package: ${{ inputs.package }}
    secrets: inherit
